//state de productos
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";

//state para el pedido
export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";

//confirmar ordenar platillo
export const CONFIRMAR_ORDENAR_PLATILLO = "CONFIRMAR_ORDENAR_PLATILLO";

//total a pagar
export const MOSTRAR_RESUMEN = "MOSTRAR_RESUMEN";

export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";

export const PEDIDO_ORDENADO = "PEDIDO_ORDENADO";

export const GUARDAR_MESA = "GUARDAR_MESA";
export const GUARDAR_ORDEN = "GUARDAR_ORDEN";

export const OBTENER_ORDENES_DIA = "OBTENER_ORDENES_DIA";
export const INICIAR_NUEVA = "INICIAR_NUEVA";

export const GUARDAR_OBJ_ORDEN = "GUARDAR_OBJ_ORDEN";

export const GUARDAR_EN_COMANDA = "GUARDAR_EN_COMANDA";
export const GUARDAR_ID_COMANDA = "GUARDAR_ID_COMANDA";
export const OBTENER_COMANDA = "OBTENER_COMANDA";
export const FINALIZAR_ORDEN = "FINALIZAR_ORDEN";

export const GUARDAR_CLIENTE_ACTUAL = "GUARDAR_CLIENTE_ACTUAL";

export const GUARDAR_COMANDA = "GUARDAR_COMANDA";
export const OBTENER_COMANDAS_DIA = "OBTENER_COMANDAS_DIA";

export const OBTENER_CLIENTES = "OBTENER_CLIENTES";
